### ISSUE TITLE
LicencePlateField Wrong Mercosul mask

### ISSUE THREAD

**Issue by Alvarocda** [edufolly/folly_fields#212]
I noticed that the LicensePlateField field is allowing you to add 2 letters to the second group of characters on the plate.

According to the new Mercosur standard, it has only 1 letter in the second group of characters, this being the second character in the group.

Ex: AAA-0A00

But the field is allowing you to add 2 letters,
Ex: AAA-0AA0

**Comment by edufolly** [comment]
Fixed #213
