### ISSUE TITLE
Add suffix widget to StringField

### ISSUE THREAD

**Issue by Alvarocda** [edufolly/folly_fields#42]
It would be nice to have suffix param that accepts a Widget in StringField.

![image](https://user-images.githubusercontent.com/12532704/139075292-eab97408-1607-432d-a83f-d4add3c72ee1.png)

**Comment by edufolly** [comment]
We have many options in `InputDecoration` to create the suffix, so I recommend using the `decoration` instead of creating new parameters in `StringField`.
